name: Workflow for Node using Snyk

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install npm
        run:  npm install -g npm@6

      - name: Install Dependencies
        run:  npm install

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
            args: test
            continue-on-error: false
            command: monitor

      - name: Install Make
        run: |
              sudo apt-get update
              sudo apt-get install -y make
    
      - name: Set up Project
        run:  make setup
          
      - name: Run Tests
        run:  make test
    
      - name: Run Linting
        run:  make lint